<?php
/* 
 * DEFINO LAS CONSTANTES QUE UTILIZO EN EL PROGRAMA
 */

// DATOS CONEXON POR MYSQL
//define("DB_DSN","mysql:host=10.8.65.9;dbname=SUCESOS");
//define("DB_DSN","mysql:dbname=web");
   


// CONEXION AL SERVIDOR SQL SERVER


define("DB_DSN","dblib:host=10.8.65.17;dbname=VISADO");
define("DB_DSN1","dblib:host=10.8.65.2;dbname=PERSONAL");

define("DB_USERNAME", "sa");
define("DB_PASSWORD", "servidor");
define("PAGE_SIZE", 5);
    

//Definicion Tablas BD
define("TBL_TIEMPO","PIOBIN_TIEMPO");


define("TBL_BDU","FICHERO_BDU");

define("ROOT", $_SERVER['HTTP_HOST']);
define("RAIZ", "http://" . $_SERVER['HTTP_HOST'] );

  
//consultas sql



define("SQL_LISTATIEMPO", "SELECT COD,TIEMPO FROM " . TBL_TIEMPOS  );


// Fin consultas tablas sux (consultas rellenar combos)

   
  

define("SQL_INSERTA_PETICION","INSERT INTO " . TBL_ESTUDIO . " (ESTADO_SOLICITUD,AN,
    NOMBRE_PACIENTE,FNACIMIENTO,CNP,CENTRO,FSOLICITUD,TLF,FSINTOMAS,PALPABLE,CM_NODULO,
    MAMAD,MAMAI,CSE,CSI,CID,CII,RETROAREOLAR,
    RETRACCION_MAMAD,RETRACCION_MAMAI,RETRACCION_RECIENT,ULCERACIOND,ULCERACIONI,
    SECRECIOND,SECRECIONI,UNILATERAL,UNIPORICA,ESPONTANEA,SEROHEMATICA,
    ENGROD,ENGROI,PNARANJAD,PNARANJAI,PATOLOGIAD,PATOLOGIAI,
    OBS,ANTECEDENTES_NO,ANTECEDENTES_MADRE,ANTECEDENTES_PADRE,ANTECEDENTES_HERMANA,ANTECEDENTES_HIJA,ANTECEDENTES_OTROS,
    THS,THS_SI,THS_FINICIO,THS_FFIN,
    BIOPSIA,BIOPSIA_MD,BIOPSIA_MI,BIOPSIA_FECHA,
    PROTESIS,PROTESIS_MD,PROTESIS_MI,
    ANTCMAMA,ANTCMAMA_MD,ANTCMAMA_MI,ANTCMAMA_FECHA,
    TRAT_QUIR,RADIOTERAPIA,QUIMIO,PREVIA,FECHA_PREVIA,PDPCM,FECHA_PDPCM,TLF2) 
    VALUES (:ESTADO_SOLICITUD,:AN,:NOMBRE_PACIENTE,:FNACIMIENTO,:CNP,:CENTRO,
    :FSOLICITUD,:TLF,:FSINTOMAS,:PALPABLE,:CM_NODULO,
    :MAMAD,:MAMAI,:CSE,:CSI,:CID,:CII,:RETROAREOLAR,
    :RETRACCION_MAMAD,:RETRACCION_MAMAI,:RETRACCION_RECIENT,:ULCERACIOND,:ULCERACIONI
    ,:SECRECIOND,:SECRECIONI,:UNILATERAL,:UNIPORICA,:ESPONTANEA,:SEROHEMATICA
    ,:ENGROD,:ENGROI,:PNARANJAD,:PNARANJAI,:PATOLOGIAD,:PATOLOGIAI,
    :OBS,:ANTECEDENTES_NO,:ANTECEDENTES_MADRE,:ANTECEDENTES_PADRE,:ANTECEDENTES_HERMANA,:ANTECEDENTES_HIJA,
    :ANTECEDENTES_OTROS,
    :THS,:THS_SI,:THS_FINICIO,:THS_FFIN,
    :BIOPSIA,:BIOPSIA_MD,:BIOPSIA_MI,:BIOPSIA_FECHA,
    :PROTESIS,:PROTESIS_MD,:PROTESIS_MI,
    :ANTCMAMA,:ANTCMAMA_MD,:ANTCMAMA_MI,:ANTCMAMA_FECHA,
    :TRAT_QUIR,:RADIOTERAPIA,:QUIMIO,:PREVIA,:FECHA_PREVIA,:PDPCM,:FECHA_PDPCM,:TLF2)");


define("SQL_BUSCA_USUARIO","SELECT NUHSA,CLAMED,ANIO,MES,DIA,APE1,APE2,NOMBRE,"
        . "IDENTIFICADOR,TELEFONO,MOVIL FROM " . TBL_BDU . " WHERE NUHSA=:NUHSA");



?>
     